<a href="https://colab.research.google.com/github/AbhirupDatta04/wpa/blob/main/notebooks/wealth_analytics_data_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install faker pandas

Collecting faker
  Downloading faker-40.11.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading faker-40.11.1-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 23.9 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.11.1

In [2]:
import pandas as pd
import random
from faker import Faker

fake = Faker()

num_users = 1000

users = []

for i in range(num_users):
    users.append({
        "user_id": i + 1,
        "signup_date": fake.date_between(start_date='-1y', end_date='today'),
        "country": random.choice(["India", "USA", "UK"]),
        "account_type": random.choice(["retail", "premium"]),
        "risk_profile": random.choice(["low", "medium", "high"])
    })

users_df = pd.DataFrame(users)

users_df.head()

   user_id signup_date country account_type risk_profile
0        1  2026-01-25   India      premium         high
1        2  2025-06-13      UK       retail         high
2        3  2025-11-15   India       retail       medium
3        4  2025-08-26      UK      premium       medium
4        5  2025-05-27      UK       retail         high

In [3]:
users_df.to_csv("users.csv", index=False)

In [4]:
users_df.head()

   user_id signup_date country account_type risk_profile
0        1  2026-01-25   India      premium         high
1        2  2025-06-13      UK       retail         high
2        3  2025-11-15   India       retail       medium
3        4  2025-08-26      UK      premium       medium
4        5  2025-05-27      UK       retail         high